// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dgsooxeqluqydyizqcww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnc29veGVxbHVxeWR5aXpxY3d3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2MDE4MDksImV4cCI6MjA1NzE3NzgwOX0.YJe175IlTKJwZyrwG_KTwOWXmw54--tBEPHjIkmWWKE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);